# Generated by Django 5.2 on 2025-05-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='end_show',
            field=models.DateTimeField(default=None),
        ),
    ]
