# Generated by Django 5.2 on 2025-05-13 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_show_end_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='end_show',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 9, 12, 35, 147913, tzinfo=datetime.timezone.utc)),
        ),
    ]
