# Generated by Django 5.2 on 2025-05-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_alter_show_end_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='end_show',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
