# Generated by Django 5.2 on 2025-05-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_alter_show_end_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='start_show',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='end_show',
            field=models.DateField(blank=True, null=True),
        ),
    ]
