# Generated by Django 5.2 on 2025-05-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_show_start_show_alter_show_end_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='end_show',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='show',
            name='start_show',
            field=models.DateField(default=None),
        ),
    ]
