# Generated by Django 5.2 on 2025-05-21 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_alter_show_end_show_alter_show_start_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='showtime',
        ),
        migrations.AlterField(
            model_name='show',
            name='end_show',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='start_show',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='ShowUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.DateTimeField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.show')),
            ],
        ),
    ]
