# Generated by Django 5.2 on 2025-05-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0008_remove_show_showtime_alter_show_end_show_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='end_show',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='start_show',
            field=models.DateTimeField(),
        ),
    ]
