# Generated by Django 5.2 on 2025-04-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('age_restrictions', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('duration', models.DurationField()),
                ('poster', models.ImageField(upload_to='media/posters/')),
            ],
        ),
    ]
