# Generated by Django 5.2 on 2025-04-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
