# Generated by Django 5.2 on 2025-05-21 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('show', '0008_remove_show_showtime_alter_show_end_show_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=20)),
                ('seat_number', models.IntegerField()),
                ('show_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.showunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('show_unit', 'row', 'seat_number')},
            },
        ),
    ]
