# Generated by Django 5.2 on 2025-05-21 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=20)),
                ('seat_number', models.IntegerField()),
                ('show_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.showunit')),
            ],
        ),
    ]
